# Generated by Django 4.0.4 on 2022-09-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='routine',
        ),
        migrations.DeleteModel(
            name='week',
        ),
    ]
