# Generated by Django 3.2.13 on 2022-05-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_to_finish',
        ),
    ]
