# Generated by Django 4.0.4 on 2022-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='time',
            field=models.TimeField(),
        ),
    ]
